name: neat-python-examples
channels:
  - conda-forge
dependencies:
  - cairo
  - cython
  - graphviz
  - gym
  - matplotlib
  - ngspice
  - pip
  - pybox2d
  - pyglet
  - python-graphviz
  - python=3.9
  - swig
  - swig
  - pygame
